language: bash

before_script:
    - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx

script:
    - bash provision/test/test_user.sh
    - bash provision/test/test_group.sh
